language: python
python:
  - "2.7"

install:
    - pip install --upgrade pip
    - pip install --process-dependency-links .
    - pip install flake8

script:
    - flake8 .
    # command to run tests
    - nosetests cosmo_cli/tests
