language: python
python:
  - "2.7"

install:

    # command to install dependencies
    - pip install .
    - pip install flake8

script:

    - flake8 .
    # command to run tests
    - pip freeze
    - source /home/travis/virtualenv/python2.7/bin/activate
    - pip freeze
    - sudo pip install --process-dependency-links .
    - pip freeze
    - nosetests cosmo_cli/tests
