public_ip: 11.0.0.7
private_ip: 11.0.0.7
ssh_key_path: ~/.vagrant.d/insecure_private_key
ssh_username: vagrant
context: {}

#compute: {agent_servers: {agents_keypair: {
#    private_key_path:
#}}}

cloudify:
    server:
        packages:
            components_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/cloudify-components_amd64.deb
            core_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/cloudify-core_amd64.deb
            ui_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/cloudify-ui_amd64.deb
    agents:
        packages:
            ubuntu_agent_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/nightly/cloudify-ubuntu-agent_amd64.deb
        config:
            min_workers: 2
            max_workers: 5
            remote_execution_port: 22
            user: vagrant
    workflows:
        task_retries: -1  # -1 means we retry forever
        retry_interval: 30

    bootstrap:
        ssh:
            initial_connectivity_retries: 20
            initial_connectivity_retries_interval: 15
            command_retries: 3
            retries_interval: 3
            connection_attempts: 1
            socket_timeout: 10
